<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CommonCostsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $commonCosts = [
            [
                'id' => 2,
                'name' => 'PER DIEM',
                'ledger_id' => 18,
                'created_by' => 17,
                'created_at' => '2023-05-15 20:17:55',
                'updated_at' => '2023-05-15 20:17:55',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 3,
                'name' => 'LASHING FEE',
                'ledger_id' => 34,
                'created_by' => 17,
                'created_at' => '2023-05-15 20:18:49',
                'updated_at' => '2023-05-15 20:18:49',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 4,
                'name' => 'COUNCIL FEE-TUNDUMA',
                'ledger_id' => 28,
                'created_by' => 17,
                'created_at' => '2023-05-15 20:19:08',
                'updated_at' => '2023-05-15 20:19:08',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 5,
                'name' => 'ROAD PERMIT',
                'ledger_id' => 20,
                'created_by' => 17,
                'created_at' => '2023-05-15 20:19:23',
                'updated_at' => '2023-05-15 20:19:23',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 6,
                'name' => 'CARBON TAX',
                'ledger_id' => 20,
                'created_by' => 17,
                'created_at' => '2023-05-15 20:20:08',
                'updated_at' => '2023-05-15 20:20:08',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 7,
                'name' => 'Council fees Nakonde/Isoka',
                'ledger_id' => 28,
                'created_by' => 17,
                'created_at' => '2023-05-15 20:20:46',
                'updated_at' => '2023-05-15 20:20:46',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 8,
                'name' => 'Council fees Kapiri',
                'ledger_id' => 28,
                'created_by' => 17,
                'created_at' => '2023-05-15 20:21:13',
                'updated_at' => '2023-05-15 20:21:13',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 9,
                'name' => 'Toll gate Chilonga',
                'ledger_id' => 21,
                'created_by' => 17,
                'created_at' => '2023-05-15 20:21:37',
                'updated_at' => '2023-05-15 20:21:37',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 10,
                'name' => 'Toll gate Kapiri',
                'ledger_id' => 21,
                'created_by' => 17,
                'created_at' => '2023-05-15 20:22:04',
                'updated_at' => '2023-05-15 20:22:04',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 11,
                'name' => 'Toll gate Kafulafuta',
                'ledger_id' => 21,
                'created_by' => 17,
                'created_at' => '2023-05-15 20:22:26',
                'updated_at' => '2023-05-15 20:22:26',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 12,
                'name' => 'Toll gate Michael Chilufya',
                'ledger_id' => 21,
                'created_by' => 17,
                'created_at' => '2023-05-15 20:22:56',
                'updated_at' => '2023-05-15 20:22:56',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 13,
                'name' => 'Toll gate Wilson Mofya',
                'ledger_id' => 21,
                'created_by' => 17,
                'created_at' => '2023-05-15 20:23:15',
                'updated_at' => '2023-05-15 20:23:15',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 14,
                'name' => 'Kasumbalesa council',
                'ledger_id' => 28,
                'created_by' => 17,
                'created_at' => '2023-05-15 20:23:36',
                'updated_at' => '2023-05-29 04:14:25',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 15,
                'name' => 'ROAD TOLL(ZAMBIA)',
                'ledger_id' => 26,
                'created_by' => 17,
                'created_at' => '2023-05-15 20:23:51',
                'updated_at' => '2023-05-15 20:23:51',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 16,
                'name' => 'DRIVER PER DIEM(USD)',
                'ledger_id' => 18,
                'created_by' => 17,
                'created_at' => '2023-05-15 20:24:12',
                'updated_at' => '2023-05-15 20:24:12',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 17,
                'name' => 'PEAGE LUBUMBASHI(USD)',
                'ledger_id' => 26,
                'created_by' => 17,
                'created_at' => '2023-05-15 20:24:39',
                'updated_at' => '2023-05-15 20:24:39',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 18,
                'name' => 'ENTRY CARD(USD)',
                'ledger_id' => 29,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:23:25',
                'updated_at' => '2023-05-15 23:23:25',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 19,
                'name' => 'DRC CROSSING FEE(USD)',
                'ledger_id' => 29,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:23:50',
                'updated_at' => '2023-05-15 23:23:50',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 20,
                'name' => 'PARKING FEE-ZAMBIA(USD)',
                'ledger_id' => 27,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:25:48',
                'updated_at' => '2023-05-15 23:25:48',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 21,
                'name' => 'DRIVER VISA(USD)',
                'ledger_id' => 23,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:26:07',
                'updated_at' => '2023-05-15 23:26:07',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 22,
                'name' => 'TRANSCORM(USD)',
                'ledger_id' => 37,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:26:28',
                'updated_at' => '2023-05-15 23:26:28',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 23,
                'name' => 'TOURISM LEVY(USD)',
                'ledger_id' => 37,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:26:46',
                'updated_at' => '2023-05-15 23:26:46',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 24,
                'name' => 'TRACKING DEVICE(USD)',
                'ledger_id' => 38,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:27:17',
                'updated_at' => '2023-05-15 23:27:17',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 25,
                'name' => 'KANYAKA PARKING',
                'ledger_id' => 27,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:27:40',
                'updated_at' => '2023-05-15 23:27:40',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 26,
                'name' => 'WHYSKY PARKING FEES(USD)',
                'ledger_id' => 27,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:27:56',
                'updated_at' => '2023-09-29 06:33:59',
                'vat' => 0,
                'editable' => 1,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 27,
                'name' => 'CHEMICAL FEE(USD)',
                'ledger_id' => 39,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:28:13',
                'updated_at' => '2023-05-15 23:28:13',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 28,
                'name' => 'CORONA TEST(USD)',
                'ledger_id' => 40,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:28:26',
                'updated_at' => '2023-10-09 02:13:19',
                'vat' => 0,
                'editable' => 1,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 29,
                'name' => 'PEAGE BULUO',
                'ledger_id' => 26,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:28:39',
                'updated_at' => '2023-05-15 23:28:39',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 30,
                'name' => 'PEAGE KIMBEIMBE',
                'ledger_id' => 26,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:28:54',
                'updated_at' => '2023-05-15 23:28:54',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 31,
                'name' => 'PEAGE LWAMBO',
                'ledger_id' => 26,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:29:06',
                'updated_at' => '2023-05-15 23:29:06',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 32,
                'name' => 'PEAGE LUALABA',
                'ledger_id' => 26,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:29:22',
                'updated_at' => '2023-05-15 23:29:22',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 33,
                'name' => 'PARKING KOLOWEZI',
                'ledger_id' => 27,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:29:37',
                'updated_at' => '2023-05-15 23:29:37',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 34,
                'name' => 'CNPR FEE',
                'ledger_id' => 35,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:29:54',
                'updated_at' => '2023-05-15 23:29:54',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 35,
                'name' => 'DOCUMENT PUSHING',
                'ledger_id' => 36,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:30:11',
                'updated_at' => '2023-05-15 23:30:11',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 36,
                'name' => 'PARKING IA-LUBUMBASHI',
                'ledger_id' => 27,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:30:28',
                'updated_at' => '2023-09-20 00:18:35',
                'vat' => 0,
                'editable' => 1,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 37,
                'name' => 'QUEUE SECURITY FEE',
                'ledger_id' => 36,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:30:53',
                'updated_at' => '2023-05-15 23:30:53',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 38,
                'name' => 'COMESA EXPENSES',
                'ledger_id' => 19,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:31:10',
                'updated_at' => '2023-05-15 23:31:10',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 39,
                'name' => 'TUNDUMA AGENCY FEE',
                'ledger_id' => 31,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:31:37',
                'updated_at' => '2023-05-15 23:31:37',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 40,
                'name' => 'DRC AGENCY FEE',
                'ledger_id' => 31,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:32:14',
                'updated_at' => '2023-05-15 23:32:14',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 41,
                'name' => 'CLEARING FEE',
                'ledger_id' => 41,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:32:27',
                'updated_at' => '2023-05-15 23:32:27',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 42,
                'name' => 'CONTAINER FEE',
                'ledger_id' => 39,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:32:42',
                'updated_at' => '2023-05-15 23:32:42',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 43,
                'name' => 'Council fees Chilabombwe',
                'ledger_id' => 28,
                'created_by' => 17,
                'created_at' => '2023-05-15 23:42:15',
                'updated_at' => '2023-05-15 23:42:15',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 44,
                'name' => 'Lualaba bridge',
                'ledger_id' => 30,
                'created_by' => 17,
                'created_at' => '2023-05-28 17:27:03',
                'updated_at' => '2023-05-28 17:27:03',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 45,
                'name' => 'Gate pass pushing',
                'ledger_id' => 36,
                'created_by' => 17,
                'created_at' => '2023-05-28 17:28:28',
                'updated_at' => '2023-05-28 17:28:28',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 46,
                'name' => 'Fuel Pulling Truck',
                'ledger_id' => 16,
                'created_by' => 17,
                'created_at' => '2023-05-28 17:29:31',
                'updated_at' => '2023-05-28 17:29:31',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 47,
                'name' => 'Fuel Semi Truck',
                'ledger_id' => 16,
                'created_by' => 17,
                'created_at' => '2023-05-28 17:30:12',
                'updated_at' => '2023-05-28 17:30:12',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 48,
                'name' => 'Driver Per diem in Dar ( Semi Truck )',
                'ledger_id' => 18,
                'created_by' => 17,
                'created_at' => '2023-05-28 17:31:00',
                'updated_at' => '2023-05-28 17:31:00',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 49,
                'name' => 'Driver Per diem in Dar ( Pulling Truck )',
                'ledger_id' => 18,
                'created_by' => 17,
                'created_at' => '2023-05-28 17:31:40',
                'updated_at' => '2023-05-28 17:31:40',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 50,
                'name' => 'Return per diem SEMI',
                'ledger_id' => 18,
                'created_by' => 17,
                'created_at' => '2023-05-28 17:32:11',
                'updated_at' => '2023-05-28 17:32:11',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 1,
            ],
            [
                'id' => 51,
                'name' => 'Kapiri-mposhi Council',
                'ledger_id' => 28,
                'created_by' => 17,
                'created_at' => '2023-05-29 04:15:48',
                'updated_at' => '2023-05-29 04:15:48',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 52,
                'name' => 'Weight Bridge fee',
                'ledger_id' => 30,
                'created_by' => 17,
                'created_at' => '2023-05-29 04:16:12',
                'updated_at' => '2023-05-29 04:16:12',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 53,
                'name' => 'Document Extension',
                'ledger_id' => 36,
                'created_by' => 17,
                'created_at' => '2023-05-29 04:23:05',
                'updated_at' => '2023-05-29 04:23:05',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 58,
                'name' => 'Driver per diem Dar',
                'ledger_id' => 18,
                'created_by' => 1,
                'created_at' => '2023-09-19 18:08:01',
                'updated_at' => '2023-09-19 18:08:01',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 59,
                'name' => 'Driver per diem Tunduma',
                'ledger_id' => 1,
                'created_by' => 1,
                'created_at' => '2023-09-19 18:08:16',
                'updated_at' => '2023-09-19 18:08:16',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 60,
                'name' => 'Driver per diem Lusaka',
                'ledger_id' => 18,
                'created_by' => 1,
                'created_at' => '2023-09-19 18:39:00',
                'updated_at' => '2023-09-19 18:39:00',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 61,
                'name' => 'Road permit & Carbon Tax',
                'ledger_id' => 20,
                'created_by' => 1,
                'created_at' => '2023-09-19 18:42:49',
                'updated_at' => '2023-09-19 18:42:49',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 62,
                'name' => 'Tollgate Katuba',
                'ledger_id' => 26,
                'created_by' => 1,
                'created_at' => '2023-09-19 18:48:34',
                'updated_at' => '2023-09-19 18:48:34',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 63,
                'name' => 'Toll gate Manyumbi',
                'ledger_id' => 21,
                'created_by' => 1,
                'created_at' => '2023-09-19 18:50:45',
                'updated_at' => '2023-09-19 18:50:45',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 64,
                'name' => 'Return Per diem PULLING',
                'ledger_id' => 18,
                'created_by' => 1,
                'created_at' => '2023-09-19 19:06:04',
                'updated_at' => '2023-09-19 19:06:04',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 1,
            ],
            [
                'id' => 65,
                'name' => 'Communal Peage',
                'ledger_id' => 26,
                'created_by' => 1,
                'created_at' => '2023-09-20 00:13:51',
                'updated_at' => '2023-09-20 00:13:51',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 66,
                'name' => 'Mobilization Per diem',
                'ledger_id' => 18,
                'created_by' => 1,
                'created_at' => '2023-09-20 00:26:11',
                'updated_at' => '2023-09-20 00:26:11',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 67,
                'name' => 'Chemafu Peage',
                'ledger_id' => 26,
                'created_by' => 1,
                'created_at' => '2023-09-20 00:59:09',
                'updated_at' => '2023-09-20 00:59:09',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 68,
                'name' => 'PEAGE SAKANIA',
                'ledger_id' => 26,
                'created_by' => 862,
                'created_at' => '2023-09-29 02:02:48',
                'updated_at' => '2023-09-29 02:02:48',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 69,
                'name' => 'SAKANIA PARKING',
                'ledger_id' => 27,
                'created_by' => 862,
                'created_at' => '2023-09-29 02:03:57',
                'updated_at' => '2023-09-29 02:03:57',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 70,
                'name' => 'Driver per diem Sakania',
                'ledger_id' => 18,
                'created_by' => 862,
                'created_at' => '2023-09-29 06:34:52',
                'updated_at' => '2023-09-29 06:34:52',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 71,
                'name' => 'Zambia Processing Fee',
                'ledger_id' => 36,
                'created_by' => 862,
                'created_at' => '2023-09-29 06:36:08',
                'updated_at' => '2023-09-29 06:36:08',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 72,
                'name' => 'CARANTEEN',
                'ledger_id' => 40,
                'created_by' => 862,
                'created_at' => '2023-09-29 06:40:54',
                'updated_at' => '2023-09-29 06:40:54',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 73,
                'name' => 'SAKANIA COUNCIL FEE',
                'ledger_id' => 28,
                'created_by' => 862,
                'created_at' => '2023-09-29 06:41:32',
                'updated_at' => '2023-09-29 06:41:32',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 74,
                'name' => 'DRHK SAKANIA',
                'ledger_id' => 40,
                'created_by' => 862,
                'created_at' => '2023-09-29 06:42:43',
                'updated_at' => '2023-09-29 06:42:43',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 75,
                'name' => 'Occ & Copies Trip Documentations',
                'ledger_id' => 88,
                'created_by' => 862,
                'created_at' => '2023-09-29 07:04:28',
                'updated_at' => '2023-09-29 07:04:28',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 76,
                'name' => 'PEAGE KAKONTWE',
                'ledger_id' => 26,
                'created_by' => 862,
                'created_at' => '2023-10-09 02:14:50',
                'updated_at' => '2023-10-09 02:14:50',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 77,
                'name' => 'PEAGE KAPUMPI',
                'ledger_id' => 26,
                'created_by' => 862,
                'created_at' => '2023-10-09 02:15:30',
                'updated_at' => '2023-10-09 02:15:30',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 78,
                'name' => 'GCLA & ABNORMAL PERMITS',
                'ledger_id' => 88,
                'created_by' => 862,
                'created_at' => '2023-10-09 04:37:47',
                'updated_at' => '2024-05-23 05:48:25',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 79,
                'name' => 'PEAGE LUFUWA',
                'ledger_id' => 26,
                'created_by' => 862,
                'created_at' => '2023-10-11 05:47:54',
                'updated_at' => '2023-10-11 05:47:54',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 80,
                'name' => 'LUFUWA PARKING',
                'ledger_id' => 27,
                'created_by' => 862,
                'created_at' => '2023-10-11 05:48:23',
                'updated_at' => '2023-10-11 05:48:23',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 81,
                'name' => 'LUFUWA COUNCIL',
                'ledger_id' => 28,
                'created_by' => 862,
                'created_at' => '2023-10-11 05:48:44',
                'updated_at' => '2023-10-11 05:48:44',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 82,
                'name' => 'PHYSICAL VERIFICATION FEES',
                'ledger_id' => 36,
                'created_by' => 862,
                'created_at' => '2023-10-18 03:25:04',
                'updated_at' => '2023-10-18 03:25:04',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 83,
                'name' => 'COBOLT FEES',
                'ledger_id' => 36,
                'created_by' => 862,
                'created_at' => '2023-11-21 04:56:55',
                'updated_at' => '2023-11-21 05:01:11',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 84,
                'name' => 'PLACARDS',
                'ledger_id' => 34,
                'created_by' => 862,
                'created_at' => '2023-11-21 05:02:56',
                'updated_at' => '2023-11-21 05:02:56',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 85,
                'name' => 'TOLL GATE KONKOLA PLAZA',
                'ledger_id' => 21,
                'created_by' => 862,
                'created_at' => '2023-12-04 04:37:10',
                'updated_at' => '2023-12-04 04:37:10',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 86,
                'name' => 'Seal Rope Fees',
                'ledger_id' => 34,
                'created_by' => 862,
                'created_at' => '2023-12-04 05:00:54',
                'updated_at' => '2023-12-04 05:00:54',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 87,
                'name' => 'TCC PEAGE',
                'ledger_id' => 26,
                'created_by' => 862,
                'created_at' => '2023-12-10 07:13:02',
                'updated_at' => '2023-12-10 07:13:02',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 88,
                'name' => 'HANRUI PEAGE',
                'ledger_id' => 26,
                'created_by' => 862,
                'created_at' => '2023-12-10 07:13:55',
                'updated_at' => '2023-12-10 07:13:55',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 89,
                'name' => 'MMT PEAGE',
                'ledger_id' => 26,
                'created_by' => 844,
                'created_at' => '2024-01-08 12:01:07',
                'updated_at' => '2024-01-08 12:01:07',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 90,
                'name' => 'URBAN PEAGE',
                'ledger_id' => 26,
                'created_by' => 862,
                'created_at' => '2024-01-13 06:19:41',
                'updated_at' => '2024-01-13 06:19:41',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 91,
                'name' => 'KPM PEAGE',
                'ledger_id' => 26,
                'created_by' => 862,
                'created_at' => '2024-01-15 05:35:52',
                'updated_at' => '2024-01-15 05:35:52',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 92,
                'name' => 'PEAGE NGUYA',
                'ledger_id' => 26,
                'created_by' => 844,
                'created_at' => '2024-02-07 10:31:00',
                'updated_at' => '2024-02-07 10:31:00',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 93,
                'name' => 'ESCORT FEES',
                'ledger_id' => 36,
                'created_by' => 862,
                'created_at' => '2024-02-08 09:14:59',
                'updated_at' => '2024-02-08 09:15:29',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 94,
                'name' => 'KINSENDA PEAGE',
                'ledger_id' => 26,
                'created_by' => 862,
                'created_at' => '2024-02-08 09:16:04',
                'updated_at' => '2024-02-08 09:16:04',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 95,
                'name' => 'MUTUKULA CITY COUNCIL FEES',
                'ledger_id' => 28,
                'created_by' => 862,
                'created_at' => '2024-02-17 06:55:46',
                'updated_at' => '2024-02-17 06:55:46',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 96,
                'name' => 'MUTUKULA AGENCY FEES',
                'ledger_id' => 31,
                'created_by' => 862,
                'created_at' => '2024-02-17 06:56:13',
                'updated_at' => '2024-02-17 06:56:13',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 97,
                'name' => 'ROAD TOLLS MUTUKULA TO MBARARA',
                'ledger_id' => 26,
                'created_by' => 862,
                'created_at' => '2024-02-17 06:56:49',
                'updated_at' => '2024-02-17 06:56:49',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 98,
                'name' => 'LOADING PER DIEM',
                'ledger_id' => 18,
                'created_by' => 862,
                'created_at' => '2024-02-17 07:03:00',
                'updated_at' => '2024-02-17 07:03:00',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 99,
                'name' => 'TOLL GATE KAVINDERE',
                'ledger_id' => 21,
                'created_by' => 844,
                'created_at' => '2024-02-23 04:10:15',
                'updated_at' => '2024-02-23 04:10:15',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 100,
                'name' => 'ROAD TOLLS JINJA',
                'ledger_id' => 26,
                'created_by' => 862,
                'created_at' => '2024-03-22 05:01:05',
                'updated_at' => '2024-03-22 05:01:05',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 101,
                'name' => 'MOVEMENT SHEET',
                'ledger_id' => 130,
                'created_by' => 862,
                'created_at' => '2024-03-22 09:55:20',
                'updated_at' => '2024-03-22 09:55:20',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 102,
                'name' => 'TRANSACTION CHARGES',
                'ledger_id' => 67,
                'created_by' => 862,
                'created_at' => '2024-03-22 09:58:55',
                'updated_at' => '2024-03-22 09:58:55',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 103,
                'name' => 'MUMBWA TOLLGATE',
                'ledger_id' => 26,
                'created_by' => 862,
                'created_at' => '2024-03-25 08:25:53',
                'updated_at' => '2024-03-25 08:25:53',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 104,
                'name' => 'MWEEKE TOLLGATE',
                'ledger_id' => 26,
                'created_by' => 862,
                'created_at' => '2024-03-25 08:26:34',
                'updated_at' => '2024-03-25 08:26:34',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 105,
                'name' => 'ROADTOLL KIGALI-RWANDA',
                'ledger_id' => 26,
                'created_by' => 862,
                'created_at' => '2024-05-02 06:22:13',
                'updated_at' => '2024-05-02 06:22:13',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 106,
                'name' => 'PEAGE MUKAMBO',
                'ledger_id' => 26,
                'created_by' => 862,
                'created_at' => '2024-06-04 09:31:28',
                'updated_at' => '2024-06-04 09:31:28',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 107,
                'name' => 'BUNGUBUNGU PEAGE',
                'ledger_id' => 26,
                'created_by' => 862,
                'created_at' => '2024-07-31 05:11:39',
                'updated_at' => '2024-07-31 05:11:39',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
            [
                'id' => 108,
                'name' => 'RADIATION FEE',
                'ledger_id' => 1,
                'created_by' => 862,
                'created_at' => '2024-08-24 04:20:48',
                'updated_at' => '2024-08-24 04:20:48',
                'vat' => 0,
                'editable' => 0,
                'advancable' => 0,
                'return' => 0,
            ],
        ];

        foreach ($commonCosts as $cost) {
            DB::table('common_costs')->updateOrInsert(
                ['id' => $cost['id']],
                $cost
            );
        }
    }
}